### ISSUE TITLE
Add an environment.yml that specifies graphchain's dependencies

### ISSUE THREAD

**Issue by lsorber** [radix-ai/graphchain#8]
And mark optional dependencies too.

Example environment.yml:
```yaml
name: graphchain-env
channels:
 - defaults
dependencies:
 - dask=0.17
 - fs-s3fs=0.1  # Optional? Dependency on `fs` already part of this package.
 - joblib=0.11
 - pip:
   - lz4~=1.1.0  # No recent version on anaconda.org.
```
